source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/schwa423/Specs.git'
platform :ios, '9.0'
#pod 'CocoaHTTPServer'
#pod 'GoogleProtobufV3', '3.0.0-alpha-3'
#pod 'gRPC'

def skeqiPods
  pod 'Google/SignIn'
  pod "PromiseKit", "~> 3.3.0"
  use_frameworks!
  pod 'Firebase', '>= 3.3.0'
  pod 'Firebase/Auth', '>= 3.3.0'
  pod 'Firebase/Database', '>= 3.3.0'
end

target 'skeqi' do
  skeqiPods
end
